version: '3.4'

services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
    command: tox
    env_file:
      - .env
    environment:
      - LANG=C.UTF-8
      - OMDB_API_KEY=${OMDB_API_KEY}
